### ISSUE TITLE
Flyme7不兼容

### ISSUE THREAD

**Issue by Felmon** [Tornaco/X-APM#252]
1. What happened（现象）:
> 主页提示已激活但不兼容， 在一应用内无法调用其他应用，比如授权登录，酷安内打开应用等等

2. Xposed logs（日志）:
```
无
```
3. Device info（设备信息）: ``` MEIZU pro6s Flyme7 7.1```

4. Frequency（出现频率）: ```Always/```

5. App version（版本）: ```5.0.7-RELEASE```

**Comment by Felmon** [comment]
没有logs，没法提取
Flyme7都有这种情况，看酷安评论区吧

**Comment by Felmon** [comment]
@Tornaco 嗯嗯 行 大概率是Flyme7内构的原因  大佬刷了7之后帮忙找找原因哈

**Comment by Tornaco** [comment]
@Felmon 👌🏻

**Comment by Felmon** [comment]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
	at android.app.Activity.startActivityForResult(Activity.java:4260)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.app.Activity.startActivityForResult(<Xposed>)
	at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(Unknown Source)
	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
	at android.app.Activity.startActivityForResult(Activity.java:4218)
	at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
	at android.app.Activity.startActivity(Activity.java:4557)
	at android.app.Activity.startActivity(Activity.java:4525)
	at github.tornaco.xposedmoduletest.ui.activity.WithWithCustomTabActivity.navigateToWebPage(Unknown Source)
	at github.tornaco.xposedmoduletest.ui.tiles.app.OpenSource$1.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5774)
	at android.view.View$PerformClick.run(View.java:22990)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
大佬 这是在x-apm内点击新手手册及源码调用浏览器时闪退。而生成的logs，之前提交的问题跟这类似。希望大佬不要放弃flyme7。。

**Comment by Felmon** [comment]
> @Felmon 👌🏻

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
at android.app.Activity.startActivityForResult(Activity.java:4260)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
at android.app.Activity.startActivityForResult()
at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(Unknown Source)
at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
at android.app.Activity.startActivityForResult(Activity.java:4218)
at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
at android.app.Activity.startActivity(Activity.java:4557)
at android.app.Activity.startActivity(Activity.java:4525)
at github.tornaco.xposedmoduletest.ui.activity.WithWithCustomTabActivity.navigateToWebPage(Unknown Source)
at github.tornaco.xposedmoduletest.ui.tiles.app.OpenSource$1.onClick(Unknown Source)
at android.view.View.performClick(View.java:5774)
at android.view.View$PerformClick.run(View.java:22990)
at android.os.Handler.handleCallback(Handler.java:836)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6564)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
大佬 这是在x-apm内点击新手手册及源码调用浏览器时闪退。而生成的logs，之前提交的问题跟这类似。希望大佬不要放弃flyme7。。

**Comment by Felmon** [comment]
@Tornaco android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1820)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
at android.app.Activity.startActivityForResult(Activity.java:4260)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
at android.app.Activity.startActivityForResult()
at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(Unknown Source)
at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
at android.app.Activity.startActivityForResult(Activity.java:4218)
at android.support.v4.app.FragmentActivity.startActivityForResult(Unknown Source)
at android.app.Activity.startActivity(Activity.java:4557)
at android.app.Activity.startActivity(Activity.java:4525)
at github.tornaco.xposedmoduletest.ui.activity.WithWithCustomTabActivity.navigateToWebPage(Unknown Source)
at github.tornaco.xposedmoduletest.ui.tiles.app.OpenSource$1.onClick(Unknown Source)
at android.view.View.performClick(View.java:5774)
at android.view.View$PerformClick.run(View.java:22990)
at android.os.Handler.handleCallback(Handler.java:836)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:203)
at android.app.ActivityThread.main(ActivityThread.java:6564)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
大佬 这是在x-apm内点击新手手册及源码调用浏览器时闪退。而生成的logs，之前提交的问题跟这类似。希望大佬不要放弃flyme7。。
