### ISSUE TITLE
异常闪退

### ISSUE THREAD

**Issue by luoxuebinfei** [Tornaco/X-APM#276]
1. What happened（现象）:
> App lock not work, no verify interface shows when I launch an app that has been added to lock list.

2. Xposed logs（日志）:
```
LOG EXAMPLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:925)
	at com.android.systemui.statusbar.policy.PreviewInflater.getTargetActivityInfo(PreviewInflater.java:164)
	at com.android.systemui.statusbar.policy.PreviewInflater.wouldLaunchResolverActivity(PreviewInflater.java:145)
	at com.android.systemui.statusbar.phone.StatusBar.startActivityDismissingKeyguard(StatusBar.java:3789)
	at com.android.systemui.statusbar.phone.StatusBar.startActivityDismissingKeyguard(StatusBar.java:3780)
	at com.android.systemui.statusbar.phone.StatusBar.handleStartActivityDismissingKeyguard(StatusBar.java:4255)
	at com.android.systemui.statusbar.phone.StatusBar.lambda$-com_android_systemui_statusbar_phone_StatusBar_180913(StatusBar.java:4251)
	at com.android.systemui.statusbar.ph
...
```
3. Device info（设备信息）: ```XiaomiRedmi5plus PixelExperience530 Android8.1```

4. Frequency（出现频率）: ```Always```

5. App version（版本）: ```May-5.0.8.1-RELEASE```

**Comment by Tornaco** [comment]
感谢反馈。
