### ISSUE TITLE
4.7.0 rc4开始错误，之前版本都没问题

### ISSUE THREAD

**Issue by zjcjgjj** [Tornaco/X-APM#29]
java.lang.NullPointerException: Attempt to invoke virtual method 'void dev.nick.eventbus.b.b.a(dev.nick.eventbus.b)' on a null object reference
	at dev.nick.eventbus.a$3.run(Unknown Source:14)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Tornaco** [comment]
感谢反馈。
