### ISSUE TITLE
应用管理在停止应用时闪退

### ISSUE THREAD

**Issue by ziyuedi** [Tornaco/X-APM#294]
1. What happened（现象）:
在应用管理中查看正在运行的应用时，点进任意一个只有进程的应用，再点击停止，应用管理就会闪退。

2. Xposed logs（日志）:
XPOSED日志不输出
这里是应用管理抓的应用管理的闪退日志（手动滑稽）
java.lang.SecurityException: Permission Denial: forceStopPackage() from pid=20498, uid=10117 requires android.permission.FORCE_STOP_PACKAGES
	at android.os.Parcel.readException(Parcel.java:1602)
	at android.os.Parcel.readException(Parcel.java:1555)
	at android.app.ActivityManagerProxy.forceStopPackage(ActivityManagerNative.java:4507)
	at android.app.ActivityManager.forceStopPackageAsUser(ActivityManager.java:2487)
	at android.app.ActivityManager.forceStopPackage(ActivityManager.java:2497)
	at github.tornaco.xposedmoduletest.ui.activity.helper.RunningServiceDetails$ActiveDetail.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5264)
	at android.view.View$PerformClick.run(View.java:21297)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

3. Device info（设备信息）: Honor 7 Huawei EMUI4.0.3 B389 Android6.0

4. Frequency（出现频率）: Sometimes

5. App version（版本）: MAY-5.0.6

**Comment by Tornaco** [comment]
Fixed.
