### ISSUE TITLE
4.7.0 rc5依旧错误

### ISSUE THREAD

**Issue by zjcjgjj** [Tornaco/X-APM#31]
java.lang.NullPointerException: Attempt to invoke virtual method 'void dev.nick.eventbus.b.b.a(dev.nick.eventbus.b)' on a null object reference
	at dev.nick.eventbus.a$3.run(Unknown Source:14)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Tornaco** [comment]
稍后请继续测试RC6， RC6添加了更多调试信息。感谢。

**Comment by zjcjgjj** [comment]
测试可以了不再崩溃，冒昧问下打盹和模糊开始修复了吗




Allen







On Tue, Mar 6, 2018 at 7:43 PM +0800, "Potesta de Tornaco" <notifications@github.com> wrote:












稍后请继续测试RC6， RC6添加了更多调试信息。感谢。

**Comment by Tornaco** [comment]
@zjcjgjj 并无准确安排 一切看时间和精力：）

**Comment by zjcjgjj** [comment]
好的。谢谢付出




Allen







On Tue, Mar 6, 2018 at 8:21 PM +0800, "Potesta de Tornaco" <notifications@github.com> wrote:












@zjcjgjj 并无准确安排 一切看时间和精力：）
