### ISSUE TITLE
兼容性故障

### ISSUE THREAD

**Issue by mymine** [Tornaco/X-APM#340]
1. What happened（现象）:
> App lock not work, no verify interface shows when I launch an app that has been added to lock list.
兼容故障。软件没有生成错误日志。

2. Xposed logs（日志）:
```
http://oeyz1bxso.bkt.clouddn.com/file-hash-zip-ab21a06ec2d6baab11d986a0f3f8245d19126.zip
LOG EXAMPLE
xxxxxxxx
xxxxxxxx
...
```
3. Device info（设备信息）: ``小米5s。MIUI10。安卓7.0``

4. Frequency（出现频率）: ```Always/Sometimes```100%

5. App version（版本）: ```5.1.3-RELEASE```

**Comment by Tornaco** [comment]
X-APM-S-WARN-**** ERROR onModuleInitError ****: github.tornaco.xposedmoduletest.xposed.submodules.ActiveServiceForegroundNotificationCancellationSubModule@320848f
07-17 20:31:10.162 I/Xposed  ( 6630): java.lang.Throwable
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.service.XAshmanServiceAbs.onModuleInitError(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.service.XAshmanServiceImpl.onModuleInitError(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.service.XModuleServiceDelegate.onModuleInitError(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.submodules.AbsSubModule.setStatus(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.submodules.AndroidSubModule.setStatus(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.submodules.ActiveServiceForegroundNotificationCancellationSubModule.hookCancelForegroundNotificationLocked(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.submodules.ActiveServiceForegroundNotificationCancellationSubModule.handleLoadingPackage(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.XModuleImplSeparable.handleLoadPackage(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at github.tornaco.xposedmoduletest.xposed.XModuleDelegate.handleLoadPackage(Unknown Source)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at de.robv.android.xposed.XposedInit$4$1.beforeHookedMethod(XposedInit.java:176)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at com.android.server.SystemServer.run(SystemServer.java:346)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at com.android.server.SystemServer.main(SystemServer.java:228)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at java.lang.reflect.Method.invoke(Native Method)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
07-17 20:31:10.162 I/Xposed  ( 6630): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
