### ISSUE TITLE
大佬，你好

### ISSUE THREAD

**Issue by Leetiantian0913** [Tornaco/X-APM#371]
HTC M9  7.1.2
App.5.1.2
只要点击右上角三点键就停止运行
崩溃日志如下
java.lang.NullPointerException: Attempt to invoke super method 'int android.support.v7.widget.DropDownListView.lookForSelectablePosition(int, boolean)' on a null object reference
	at android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.lookForSelectablePosition(Unknown Source)
	at android.support.v7.widget.MenuPopupWindow.createDropDownListView(Unknown Source)
	at android.support.v7.widget.ListPopupWindow.buildDropDown(Unknown Source)
	at android.support.v7.widget.ListPopupWindow.show(Unknown Source)
	at android.support.v7.view.menu.StandardMenuPopup.tryShow(Unknown Source)
	at android.support.v7.view.menu.StandardMenuPopup.show(Unknown Source)
	at android.support.v7.view.menu.MenuPopupHelper.showPopup(Unknown Source)
	at android.support.v7.view.menu.MenuPopupHelper.tryShow(Unknown Source)
	at android.support.v7.view.menu.MenuPopupHelper.show(Unknown Source)
	at android.support.v7.widget.PopupMenu.show(Unknown Source)
	at github.tornaco.xposedmoduletest.ui.activity.common.CommonPackageInfoListActivity.showCommonItemPopMenu(Unknown Source)
	at github.tornaco.xposedmoduletest.ui.activity.lazy.LazyAppNavActivity$1.onItemClickNoneChoiceMode(Unknown Source)
	at github.tornaco.xposedmoduletest.ui.adapter.common.CommonPackageInfoAdapter.lambda$onBindViewHolder$2$CommonPackageInfoAdapter(Unknown Source)
	at github.tornaco.xposedmoduletest.ui.adapter.common.CommonPackageInfoAdapter$$Lambda$2.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5662)
	at android.view.View$PerformClick.run(View.java:22563)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6521)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:969)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by Tornaco** [comment]
Dup with #372
