### ISSUE TITLE
所有应用“已停止运行”

### ISSUE THREAD

**Issue by SanbornWen** [Tornaco/X-APM#397]
一加3T，Android 8.1.0，魔趣ROM，

**Comment by SanbornWen** [comment]
Trace路径下的日志：
Thread[android.bg,5,main]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.PersistableBundle.getBoolean(java.lang.String)' on a null object reference
	at com.android.server.location.GnssLocationProvider.subscriptionOrSimChanged(GnssLocationProvider.java:540)
	at com.android.server.location.GnssLocationProvider.-wrap42(Unknown Source:0)
	at com.android.server.location.GnssLocationProvider$ProviderHandler.handleMessage(GnssLocationProvider.java:2242)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
