### ISSUE TITLE
后台不停的刷错误日志

### ISSUE THREAD

**Issue by monkey000** [Tornaco/X-APM#399]
Android 9,LinageOS16
magisk + riru ExXposed
使用时没有什么异常
但是后台不停的输出错误日志

> 03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: java.lang.ClassCastException: com.android.server.notification.NotificationRecord cannot be cast to android.service.notification.StatusBarNotification
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	**at github.tornaco.xposedmoduletest.xposed.submodules.NotificationManagerServiceSubModule$2.afterHookedMethod(Unknown Source:8)**
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(Unknown Source:0)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at EdHooker89.hook(Unknown Source:157)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at com.android.server.notification.NotificationManagerService$PostNotificationRunnable.run(NotificationManagerService.java:4509)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:873)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:193)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at com.android.server.SystemServer.run(SystemServer.java:480)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at com.android.server.SystemServer.main(SystemServer.java:302)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-04 17:58:55.109  2594  2594 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)

**Comment by keith-xiong** [comment]
这名字……今晚刚好下雨，看到提醒时还以为我什么时候订了天气预报😂

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

**Comment by Tornaco** [comment]
9.0还是有不少Hook点需要修改。
